nelmio_api_doc:
  documentation:
    info:
      title: "Payment Gateway API"
      description: "Unified API to handle payment gateways"
      version: "1.0.0"
  areas:
    path_patterns: [ ^/payment ]