services:
  symfony:
    build:
      context: ./
      dockerfile: Dockerfile
    image: symfony-app
    container_name: symfony-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - symfony
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/config.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
    depends_on:
      - symfony

networks:
  symfony:
    driver: bridge
